# Generated by Django 3.2.7 on 2024-01-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
