# Generated by Django 3.2.7 on 2024-01-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
    ]
