# Generated by Django 3.2.7 on 2024-01-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_product_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
    ]
